update packages
fslaborg/XPlot pull request #179
Opened 2023-11-23 09:01 UTC by colombod

upgrading test tfm to net7.0
upgrade to .NET Interactive and other pacakges
upgraded Newtonsoft to latest

2023-11-23 09:50 UTC, colombod commented
@cartermp I think I need some holding hands on this ...

2023-11-23 14:13 UTC, cartermp commented
I think maybe you just need to bump the global.json and the github runners?

2023-11-23 14:33 UTC, colombod commented
> I think maybe you just need to bump the global.json and the github runners?

Global.json seems fine

2023-11-23 16:38 UTC, cartermp commented
Ugh. So I'm pretty sure this is a FAKE issue: https://github.com/fsprojects/FAKE/issues/2753

2023-11-23 16:39 UTC, cartermp commented
See also: https://github.com/fsprojects/FAKE/issues/2719

So if we need .NET 7+ support, we need to rip out FAKE. It's honestly not a bad idea, FAKE is typically nothing but trouble for the past several years

2024-04-24 13:48 UTC, cartermp commented on src/XPlot.Plotly.Interactive/XPlot.Plotly.Interactive.fsproj
> +        <Description>Enables XPlot.Plotly to be used in .NET Interactive. When you use this package, you can embed Plotly charts directly into a .NET Interactive notebook!</Description>
```suggestion
        <Description>Lets you use XPlot.Plotly to be used in .NET Interactive. When you use this package, you can embed Plotly charts directly into a .NET Interactive notebook!</Description>
```

2024-04-24 14:00 UTC, cartermp requested changes
@colombod Good news, we're unblocked on the build, but the Fsharp.Core reference is messing up some tests. I think we need to bump them back down.

2024-04-24 14:00 UTC, cartermp commented on src/XPlot.Plotly/XPlot.Plotly.fsproj
> +    <PackageReference Update="FSharp.Core" Version="8.0.100" />
@colombod I believe this needs to be bumped back down

2024-04-24 14:00 UTC, cartermp commented on src/XPlot.Plotly.Interactive/XPlot.Plotly.Interactive.fsproj
> +    </ItemGroup>
I think we should also not pull in latest FSharp.Core here, esp. since it's an older TFM (.NET 7)

2024-04-24 16:51 UTC, colombod commented
That could make it a problem with net interactive?

2024-11-15 01:57 UTC, cartermp commented
Closing as dealt with in latest main

2024-11-15 01:57 UTC, closed without merging